/*
 * This file is generated by jOOQ.
*/
package com.repository;


import com.repository.tables.TbBook;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookdb extends SchemaImpl {

    private static final long serialVersionUID = 1704218301;

    /**
     * The reference instance of <code>bookdb</code>
     */
    public static final Bookdb BOOKDB = new Bookdb();

    /**
     * The table <code>bookdb.tb_book</code>.
     */
    public final TbBook TB_BOOK = com.repository.tables.TbBook.TB_BOOK;

    /**
     * No further instances allowed
     */
    private Bookdb() {
        super("bookdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TbBook.TB_BOOK);
    }
}
