/*
 * This file is generated by jOOQ.
*/
package com.repository;


import com.repository.tables.TbBook;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bookdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bookdb.tb_book</code>.
     */
    public static final TbBook TB_BOOK = com.repository.tables.TbBook.TB_BOOK;
}
